
server:
  port: 8892 #端口号可以自定义
  #ssl:
    #enabled: true
    #key-store: classpath:keystore.p12
    #key-store: file:/root/test/keystore.p12
    #key-store-password: 123456
    #key-store-type: PKCS12
    #key-alias: server
    #key-password: 123456
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  thymeleaf:
    cache: false
  freemarker:
    cache: false

logging:
  file:
    path: /home/srm/log
# jwt令牌
jwt:
  # JWT存储的请求头
  # 正常前端请求 tokenHeader：Authorization 是key tokenHead：Bearer是它的 value 加上空格然后jwt令牌，组成一个请求
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer

  #keytool -genkeypair -alias springboot -keyalg EC -keysize 256 -validity 365 -keypass 123456 -keystore EC_keystore.jks -storepass 123456 -storetype jks

uniPush:
  appId: UexSDZthjX78ZIVIKGn6s2
  appKey: ofD55yw8477RyDaJbn4A08
  masterSecret: VuHdS3rWxn6EWhH9GIt8S3
  appSecret: OV6LcLSB6YAj2WriwaOCg2
qyWx:
  corPid: ww3ea32d55564cabcd
  corpSecret: mRlQugj17BOfoWXeOnU0xkz6shqVoOTumhieicPzmTk
  agentid: 1000002
bdqWx:
  corPid: ww5e8f9a58d8145b4d
  corpSecret: xoqFdoaJo2WZIYjgeAoiAUgjMOc3R6_88TVaLP-zhQA
  agentid: 1000105

cacheinfo:
  #url: https://111.203.238.144:1443/imedical/rest/open/requestMethod
  url: https://172.31.61.100:1443/imedical/rest/open/requestMethod
  userName: _SYSTEM
  passWord: ia8Ev8b#6W
ftpinfo:
  ip: 172.31.61.100
  port: 2121
  ftpUser: materialsftp
  passWord: Ct0%ENOiJ
  path: srm
  mainPath: /dthealth/dhccftp/materialsftp
ftpinfo2:
  ip: 175.24.134.85
  port: 22
  ftpUser: postStoreFtp
  passWord: 456aaasss@A
  path: srm
  mainPath: /data
minio2:
  endpoint: http://172.16.37.112:9099
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: kysrm

minio:
  endpoint: http://175.24.134.85:9000
  accessKey: adminsrm
  secretKey: 456qweQaz
  bucketName: kysrm